"""Generate a compilable Objective-C NSXPC client skeleton from a protocol.

Consumes the JSON produced by :func:`collectors.nsxpc.extract_protocols` and
emits a self-contained ``main.m`` that declares the protocol, connects to the
Mach service, and calls one selector with ``NSNull`` / empty args (and a logging
completion block for trailing blocks). Compiles with::

    clang -fobjc-arc -framework Foundation main.m -o client
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional


def _c_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _declaration(method: Dict[str, Any]) -> str:
    """The @protocol method line, from the extracted signature."""
    return method.get("signature", f"- (void){method.get('name', '')}") + ";"


def _call(remote_var: str, method: Dict[str, Any]) -> str:
    """Build the ``[remote selector:NSNull ...]`` message for one method."""
    name = method.get("name") or ""
    args = method.get("args") or []
    labels = name.split(":")[:-1]
    if not labels and not args:
        return f"[{remote_var} {name}]"
    exprs: List[str] = []
    has_block = False
    for i, a in enumerate(args):
        if a.get("is_block"):
            has_block = True
            exprs.append(
                "^(id result, NSError *error) {\n"
                "        NSLog(@\"reply: %@ error: %@\", result, error);\n"
                "        exit(error ? 1 : 0);\n"
                "    }"
            )
        else:
            exprs.append("[NSNull null]")
    parts = [f"{labels[i] if i < len(labels) else 'arg'}:{expr}" for i, expr in enumerate(exprs)]
    return f"[{remote_var} " + " ".join(parts) + "]", has_block


def _select_method(methods: List[Dict[str, Any]], selector: Optional[str]) -> Dict[str, Any]:
    if not methods:
        raise ValueError("the protocol carries no methods to call")
    if selector is None:
        return methods[0]
    for m in methods:
        if m.get("name") == selector:
            return m
    for m in methods:
        if selector in (m.get("name") or ""):
            return m
    raise ValueError(f"no method matching {selector!r}")


def generate_main_m(protocol: Dict[str, Any], mach_service: str,
                    selector: Optional[str] = None) -> str:
    """Render a self-contained ``main.m`` for *protocol* (an extract dict)."""
    name = protocol.get("name", "RemoteProtocol")
    methods = protocol.get("methods") or []
    chosen = _select_method(methods, selector)
    call, has_block = _call("remote", chosen)

    decls = "\n".join(_declaration(m) for m in methods)

    body = f"        {call};\n"
    if not has_block:
        body += f"        NSLog(@\"called {_c_string(chosen.get('name', ''))}\");\n"

    return f"""// Generated by macOS-TBM `tbm clientgen` — a minimal NSXPC test client.
//
// Compile:
//   clang -fobjc-arc -framework Foundation main.m -o client
//
// This is a *skeleton*: it calls one selector with NSNull / empty arguments and
// prints the reply or error. Fill in real arguments and block signatures before
// relying on it for anything but reachability/entitlement checks.

#import <Foundation/Foundation.h>
#import <stdlib.h>

@protocol {name}
{decls}
@end

int main(int argc, const char *argv[]) {{
    @autoreleasepool {{
        NSString *machService = @"{_c_string(mach_service)}";
        NSXPCConnection *conn = [[NSXPCConnection alloc] initWithMachServiceName:machService
                                                                        options:0];
        conn.remoteObjectInterface = [NSXPCInterface interfaceWithProtocol:@protocol({name})];
        [conn resume];

        id<{name}> remote = [conn remoteObjectProxyWithErrorHandler:^(NSError *error) {{
            NSLog(@"XPC error: %@", error);
            exit(1);
        }}];

{body}
        [[NSRunLoop currentRunLoop] run];
    }}
    return 0;
}}
"""
